#!/usr/bin/zsh

# This should set BDW_CONFIG_TYPE at minimum.
source ~/.bdwconfig

# Umask
umask 027

# Load user functions.
# fpath=(~/.zsh/functions* $fpath)
# autoload -U ~/.zsh/functions*/*(:t)

autoload -U zmv
autoload run-help
autoload -U url-quote-magic
autoload -Uz vcs_info
autoload -U colors

zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:*' stagedstr '%F{yellow}●'
zstyle ':vcs_info:*' unstagedstr '%F{red}●'
zstyle ':vcs_info:*' formats '%u%c %F{green}%b %F{default}'
zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:*' get-revision  true

# Enable auto-execution of functions.
PERIOD=300
typeset -ga preexec_functions
typeset -ga precmd_functions
typeset -ga periodic_functions
precmd_functions+='vcs_info'
precmd_functions+='precmd_term_title'
preexec_functions+='preexec_term_title'
periodic_functions+='conf-prompt-helper'

# History settings
HISTFILE=~/.zsh_history
HISTSIZE=20000
SAVEHIST=20000

# Setup ZSH variables.
cdpath=(. ~ ~/working_code)
fignore=(\~)
watch=(all)
DIRSTACKSIZE=20
HISTFILE=~/.zsh_history
HISTSIZE=20000
LISTMAX=0
LOGCHECK=60
MAILCHECK=1
READNULLCMD=less
REPORTTIME=15
SAVEHIST=20000
TIMEFMT='%J  %*U user %*S system %P cpu (%*E wasted time).'
WATCHFMT='%n %a %l from %m at %t.'
WORDCHARS=${WORDCHARS//[\/]}

# Just in case, force emacs mode
bindkey -e

# zle settings
# fake-enter = save to history without executing.
zle -N fake-enter; bindkey "^X^H" fake-enter
zle -N self-insert url-quote-magic

# Navigation options
setopt \
  auto_cd \
  auto_name_dirs \
  autopushd \
  cdable_vars \
  pushdignoredups \
  pushdminus \
  pushdsilent \
  pushdtohome \

# CLI options
setopt \
  correct \
  correct_all \
  prompt_subst

# History options
setopt \
  append_history \
  hist_allow_clobber \
  hist_find_no_dups \
  hist_ignore_all_dups \
  hist_ignore_dups \
  hist_ignore_space \
  hist_save_no_dups \
  inc_append_history \
  share_history \

# Define aliases.
alias cd/='cd /'
alias cd..='cd ..'
alias cd...='cd ../..'
alias cp='nocorrect cp -i'
alias d='dirs -v'
alias dlbf='rm -f (.*~|*~)'
alias dlb='rm  -i (.*~|*~)'
alias grep=egrep
alias h=history
alias j=jobs
alias lc='ls -h -l --color=yes | less'
alias lca='ls -h -l -A --color=yes | less'
alias lld='ls -ld *(-/DN)'
alias ll='ls -lh'
alias mkdir='nocorrect mkdir'
alias mmv='noglob zmv -W'
alias mv='nocorrect mv -i'
alias po=popd
alias pu=pushd
alias rdlbf='find . -iname \*~ | xargs rm -f'
alias rezsh='nocorrect exec $SHELL'
alias rm='rm -i'
alias sudosh='nocorrect sudo $SHELL'
alias zmv='noglob zmv'

alias -g G="egrep"
alias -g H=' | head'
alias -g L=' | less'
alias -g T=' | tail'

# Set up $fg[red], etc
colors
PROMPT="%B%{$fg[green]%}%n%{$reset_color%}%b @ %B%{$fg[blue]%}%m%b %{$reset_color%}: %{$fg[red]%}%3~
%{$reset_color%}(%?) %# "
RPROMPT=$'${vcs_info_msg_0_}'

