#!/bin/bash

set -e

BDW_CONFIG_FILE="~/.bdwconfig"
if [[ -f "${BDW_CONFIG_FILE}" ]]; then
    source "${BDW_CONFIG_FILE}"
fi

export BDW_CONFIG_TYPE="${BDW_CONFIG_TYPE:-home}"

SCRIPT_DIR="$(dirname $0)/scripts"

echo Running Scripts from "'"${SCRIPT_DIR}"'"

run-parts -v "${SCRIPT_DIR}"
