#!/bin/bash

# Watch for Google Meet windows being in an active call. When found, inhibit
# idle for 60.

while true; do
  meet_windows=$(swaymsg -t get_tree | grep -E 'title.*Meet - .* - Google Chrome')
  if [ -n "${meet_windows}" ]; then
    systemd-inhibit --what=idle --who=auto-inhibit --why='Video call active' --mode=block sleep 30 &
    echo -n "Found some: "
    echo $meet_windows
  fi
  sleep 31
done
