#!/bin/bash

set -u
set -e

source ~/.bdwconfig
export BDW_CONFIG_TYPE="${BDW_CONFIG_TYPE:-home}"

# A wrapper for ssh so we can inject a $BDW_CONFIG_TYPE handler for
# things like special key management.

HELPER="${HOME}/.bdwscripts-${BDW_CONFIG_TYPE}/ssh-helper"

if [ -x "${HELPER}" ]; then
    "${HELPER}" $@
fi

case "$@" in
  *benandwen.net)
    # Until we sort out ssh agent forwarding with mosh, use ssh
    # exec mosh $@
    exec mosh --family=inet --server="systemd-run --scope --user mosh-server" $@
    ;;
  *)
    exec ssh $@
    ;;
esac
