#!/bin/bash

# We always want emacs started with a 24-bit terminfo because our
# themes depend on that. As we have emacs 27 in play still, it doesn't
# understand the COLORTERM environment variable, so we use a custom
# terminfo file for that. But we also have emacs 28 in places, so we
# export COLORTERM too.

export TERM=xterm-24bit
export COLORTERM=truecolor

exec emacsclient -nw --alternate-editor= $@
