#!/bin/bash

# We expect this to be triggered from inputplug so that every time we
# change keyboards, we redo our preferences. This should help with our
# laptop that adds and removes an external keyboard when docked.

setxkbmap \
    -layout us \
    -variant altgr-intl \
    -option nodeadkeys \
    -option "" \
    -option "ctrl:nocaps" \
    -option "caps:ctrl_modifier" \
    -option "eurosign:4" \
    -option "lv3:menu_switch"
