#!/usr/bin/env python3

import os
import i3ipc

def on_shutdown(conn):
    os.system("systemctl stop --user emacs")
    return

conn = i3ipc.Connection()
conn.on('ipc_shutdown', on_shutdown)

conn.main()
