#!/bin/bash

# Ensure that if we hit the hotkey to launch emacsclient, we don't run multiple.

(
    if ! flock -n -x 0; then
        # We're already running and emacs should be visible,
        # so make sway focus the scratchpad and exit.
        swaymsg scratchpad show
        exit 0
    fi

    /usr/bin/emacsclient -c
) <$0
