#!/bin/bash

BARNAME="i3main"
LOGFILE="/tmp/polybar-${BARNAME}.log"

exec >>${LOGFILE} 2>&1

echo "--- $(date +%c) ($@) ---"
echo "Stopping any running polybar instances."
polybar-msg cmd quit

sleep 1

echo "Starting appropriate new instances, per monitor."
for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    echo "Starting for ${m}"
    MONITOR="$m" polybar --reload --config=~/.config/polybar/config.ini "${BARNAME}" &
    disown
done
