#!/bin/bash

PRIMARY_MONITOR="$(xrandr --listmonitors | grep '\*' | cut -d' ' -f6)"

# Terminate any running bars so we always set up on current monitors
# with current config.
polybar-msg cmd quit

for monitor in $(polybar --list-monitors | cut -d":" -f1); do
    LOGFILE="/tmp/polybar-${monitor}.log"

    exec >>${LOGFILE} 2>&1
    echo "--- $(date +%c) ---"
    echo "Starting for ${monitor}"

    case "${monitor}" in
    "${PRIMARY_MONITOR}")
        MONITOR="${monitor}" polybar --reload "primary" &
        disown
        ;;
    *)
        MONITOR="${monitor}" polybar --reload "secondary" &
        disown
        ;;
    esac
done
