#!/bin/bash

case "$1" in
  "lock")
    pactl set-sink-mute 0 1
    (swaylock -e; "$0" unlock) &
    ;;
  "unlock")
    if pgrep swaylock; then
      swaymsg "output * dpms on"
    fi
    pactl set-sink-mute 0 0
  ;;
esac
