#!/bin/bash

set -e
set -u

selection=$(
  printf "Logout\nReboot\nShutdown\n" |
    tofi --prompt-text="" \
      --hide-input=true \
      --hide-cursor=true \
      --padding-left=45% \
      --padding-top=35% \
      --require-match=true)

if [ -n "${selection}" ]; then
  confirmation=$(printf "Yes\nNo\n" |
    tofi --prompt-text="Really ${selection}?: " \
      --require-match=true \
      --hide-cursor=true \
      --padding-left=35% \
      --padding-top=45% \
      --require-match=true \
      --horizontal=true)

  case "${confirmation}" in
    "Yes")
    ;;
    *)
      exit 0
    ;;
  esac
else
    exit 0
fi

case "${selection}" in
  "Logout")
    swaymsg exit
    ;;
  "Reboot")
    shutdown -r now
    ;;
  "Shutdown")
    shutdown -h now
    ;;
esac
