#!/bin/bash

# Download and install Adobe's Source Code Pro fonts

SF_NET="http://sourceforge.net"
FONT_VERSION="1.017"
FONT_FILE="SourceCodePro_FontsOnly-${FONT_VERSION}.zip"
FONT_DIR="$(basename ${FONT_FILE} .zip)"
URL="${SF_NET}/projects/sourcecodepro.adobe/files/${FONT_FILE}/download"

ZIPFILE="/tmp/scp_fonts.zip"
TMPDIR="/tmp/${FONT_FILE}"

HOME_FONTS="${HOME}/.fonts"

wget -O "${ZIPFILE}" "${URL}"

if [ ! -d "${HOME_FONTS}" ]; then
    mkdir "${HOME_FONTS}"
fi

cd "$(dirname ${ZIPFILE})"
unzip -o "${ZIPFILE}"

cd "${FONT_DIR}"

for f in TTF/* OTF/*; do
    cp "${f}" "${HOME_FONTS}"
done

cd ..
rm -rf "${FONT_DIR}"
rm "${ZIPFILE}"

fc-cache "${HOME_FONTS}"
