#!/bin/bash

# Download and install Adobe's Source Code Pro fonts

HOME_FONTS="${HOME}/.fonts"
HOME_SCP="${HOME_FONTS}/scp"

[ -d "${HOME_SCP}" ] || mkdir -p "${HOME_SCP}"

git clone https://github.com/adobe-fonts/source-code-pro.git "${HOME_SCP}"
fc-cache -f -v "${HOME_FONTS}"
