#!/bin/bash

BASE_PATH="$(dirname $0)/../"
PACKAGES_FILE="${BASE_PATH}/debian_packages"
# A list of debian packages we expect in our environment.
readarray -t PACKAGES < "${PACKAGES_FILE}"

echo "Installing packages:"
echo "${PACKAGES[@]}"
sudo apt-get -qq install ${PACKAGES[@]}
