#!/bin/bash

# A list of debian packages we expect in our environment.
PACKAGES=(
    autorandr
    colordiff
    dex
    gconf2
    gnome-screensaver
    i3
    inputplug
    keychain
    pulseaudio-utils
    rofi
    thunar
    tmux
    xautolock
)

echo "Installing packages: ${PACKAGES[@]}"
sudo apt-get -qq install ${PACKAGES[@]}
