#!/bin/bash

BDW_CONFIG_TYPE="${BDW_CONFIG_TYPE:-home}"
BDW_CONFIG_FILE=~/.bdwconfig

if [[ ! -f "$BDW_CONFIG_FILE" ]]; then
    echo "Setting BDW_CONFIG_TYPE to '${BDW_CONFIG_TYPE}'"
    echo "BDW_CONFIG_TYPE='${BDW_CONFIG_TYPE}'" >"${BDW_CONFIG_FILE}"
    echo >>"${BDW_CONFIG_FILE}"
else
    echo "${BDW_CONFIG_FILE} is already in place."
fi

# Update this file, in case it still carries the export statement. To use it as
# a systemd EnvironmentFile, it needs to be use VAR=VAL.
perl -pi -e 's/export //' "${BDW_CONFIG_FILE}"
