#!/bin/bash

set -e

SCRIPT_DIR="$(realpath $(dirname $0))"
GCONF_SETTINGS="$(realpath -s "${SCRIPT_DIR}/../gconf_settings")"

if [ -f "${GCONF_SETTINGS}" ]; then
    while read key type value; do
	echo "Setting ${key} to '${value}'"
	gconftool-2 --set "${key}" --type ${type} "${value}"
    done < <(grep -v '^#' "${GCONF_SETTINGS}")
else
    echo "${GCONF_SETTINGS} not found..."
fi
