#!/bin/bash

set -e

SCRIPT_DIR="$(realpath $(dirname $0))"
DCONF_SETTINGS="$(realpath -s "${SCRIPT_DIR}/../dconf_settings")"

if [ -f "${DCONF_SETTINGS}" ]; then
    while read key value; do
	echo "Setting ${key} to '${value}'"
	dconf write "${key}" "${value}"
    done < <(grep -v '^#' "${DCONF_SETTINGS}")
else
    echo "${DCONF_SETTINGS} not found..."
fi
