#!/bin/bash

set -e

SSH_DIR="$(realpath ~/.ssh)"

chmod 700 "${SSH_DIR}"
chmod 600 "${SSH_DIR}/config"

case "${BDW_CONFIG_TYPE}" in
  "home")
    echo "Setting up ${SSH_DIR}..."
    cd "${SSH_DIR}"
    make
    ;;
  *)
    echo "Nothing to do for ssh in BDW_CONFIG_TYPE=${BDW_CONFIG_TYPE}."
    ;;
esac
