#!/bin/bash

set -e

# We have a local .config/systemd/ service file for emacs so we can
# easily bounce our daemon.
systemctl daemon-reload --user
systemctl enable --user emacs
systemctl restart --user emacs
