#!/bin/bash

set -e

# Write out the current value for SSH_AUTH_SOCK to a file that gets
# sourced by the systemd unit.
ENVD="${HOME}/.config/environment.d"

[ -d "${ENVD}" ] || mkdir -p "${ENVD}"

cat <<EOF >${ENVD}/emacs.service.conf
SSH_AUTH_SOCK=${SSH_AUTH_SOCK}
EOF

# We have a local .config/systemd/ service file for emacs so we can
# easily bounce our daemon.
systemctl daemon-reload --user
systemctl enable --user emacs
systemctl restart --user emacs
