#!/bin/bash

BASE_PATH="$(realpath $(dirname $0)/../)"
SYSTEMD_BASE="${BASE_PATH}/systemd-user"
SYSTEMD_DIR="${HOME}/.config/systemd/user"

cd "${BASE_PATH}"

[ -d "${SYSTEMD_DIR}" ] || mkdir -p "${SYSTEMD_DIR}"

SERVICES="$(
    cd ${SYSTEMD_BASE}
    ls
)"

for service in ${SERVICES}; do
    serv=$(basename ${service})
    ln -f "${SYSTEMD_BASE}/${serv}" "${SYSTEMD_DIR}/${serv}"
    systemctl enable --user ${serv}

done

# Ensure this is enabled
systemctl --user enable ssh-agent.socket

# We have a local .config/systemd/ service file for emacs so we can
# easily bounce our daemon.
systemctl daemon-reload --user

sudo loginctl enable-linger $USER

LCDIR=/etc/systemd/logind.conf.d
sudo bash -c "[ -d \"${LCDIR}\" ] || mkdir \"${LCDIR}\"; cat <<EOF > \"${LCDIR}/kill-user-processes.conf\"
# Set by bdwconfig
[Login]
KillUserProcesses=yes
EOF"
