#!/bin/bash

set -e

SCRIPT_DIR="$(realpath $(dirname $0))"
BASE_DIR="$(realpath -s "${SCRIPT_DIR}/../")"
ENV_DIR="${BASE_DIR}-${BDW_CONFIG_TYPE}"

case "${BDW_CONFIG_TYPE}" in
    work)
	echo
	echo "---------- Setting up $(basename "${ENV_DIR}") ----------"
	if [[ ! -d "${ENV_DIR}" ]]; then
	    git clone -q sso://user/bdwalton/bdwconfig-work "${ENV_DIR}"
	fi

	cd "${ENV_DIR}"
	git pull -q origin main
	./setup-env
	;;
    *)
	echo "Nothing special to do for BDW_CONFIG_TYPE='${BDW_CONFIG_TYPE}'."
	;;
esac

